### ISSUE TITLE
Support RKE2 clusters version 1.27+

### ISSUE THREAD

**Issue by mavynet** [rancher-sandbox/cluster-api-provider-rke2#162] opened 2023-08-09 13:06 UTC
**Describe the solution you'd like:**
In order to deploy RKE2 1.27.3+rke2r1 clusters we need a newer version of k8s.io/client-go (the current v0.26.1 works ok with 1.26.7+rke2r1)

**Why do you want this feature:**
Currently, deploying workload clusters with RKE2 1.27.3+rke2r1 we encounter the following error which causes the rke2-controller to fail:
```bash
I0808 14:33:18.117359       1 controller.go:118]  "msg"="Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" "RKE2ControlPlane"={"name":"first-workload-cluster-control-plane","namespace":"workload-cluster"} "controller"="rke2controlplane" "controllerGroup"="controlplane.cluster.x-k8s.io" "controllerKind"="RKE2ControlPlane" "name"="first-workload-cluster-control-plane" "namespace"="workload-cluster" "reconcileID"="a48654ec-f0a8-4366-a3f3-dfe9ab011edf"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12c3630]
```

**Comment by tmmorin** [comment] 2023-08-09 16:09
hello @belgaied2 

does this sound reasonable to you ?

**Comment by belgaied2** [comment] 2023-08-12 10:10
Yes, this is definitely reasonable. We will need to check the compatibility of the library with older kubernetes versions.

**Comment by belgaied2** [comment] 2023-08-18 13:13
I am not able to reproduce the problem with the current code when deploying RKE2 v1.27.3+rke2r1:
```
k get machine -n test-1-27
NAME                                 CLUSTER     NODENAME                                       PROVIDERID                                                PHASE     AGE    VERSION
rke2-1-27-control-plane-fscj6        rke2-1-27   rke2-1-27-control-plane-fscj6                  docker:////rke2-1-27-control-plane-fscj6                  Running   133m   v1.27.3
rke2-1-27-control-plane-jqhxj        rke2-1-27   rke2-1-27-control-plane-jqhxj                  docker:////rke2-1-27-control-plane-jqhxj                  Running   128m   v1.27.3
rke2-1-27-control-plane-wvw8m        rke2-1-27   rke2-1-27-control-plane-wvw8m                  docker:////rke2-1-27-control-plane-wvw8m                  Running   131m   v1.27.3
worker-md-0-5db9b8cc6fxdk6xz-6tlpk   rke2-1-27   rke2-1-27-worker-md-0-5db9b8cc6fxdk6xz-6tlpk   docker:////rke2-1-27-worker-md-0-5db9b8cc6fxdk6xz-6tlpk   Running   4h     v1.27.3
worker-md-0-5db9b8cc6fxdk6xz-cw4cp   rke2-1-27   rke2-1-27-worker-md-0-5db9b8cc6fxdk6xz-cw4cp   docker:////rke2-1-27-worker-md-0-5db9b8cc6fxdk6xz-cw4cp   Running   4h     v1.27.3
```
@mavynet Are you sure this is caused by client-go version ?

**Comment by mavynet** [comment] 2023-08-22 10:23
Hi @belgaied2 
I did another try, but the same happens:
When the cluster gets deployed everything looks fine:
```bash
root@bastion-nis-nat:~/cm-tests/sylva-core# kubectl --kubeconfig management-cluster-kubeconfig -n rke2-control-plane-system get pods
NAME                                                     READY   STATUS    RESTARTS   AGE
rke2-control-plane-controller-manager-85bc4bc7c9-jlr98   1/1     Running   0          24m
root@bastion-nis-nat:~/cm-tests/sylva-core# kubectl --kubeconfig management-cluster-kubeconfig -n rke2-bootstrap-system get pods
NAME                                                 READY   STATUS    RESTARTS   AGE
rke2-bootstrap-controller-manager-68c4bc48f7-xbt4m   1/1     Running   0          24m
root@bastion-nis-nat:~/cm-tests/sylva-core# kubectl --kubeconfig management-cluster-kubeconfig get machines -A
NAMESPACE          NAME                                                          CLUSTER                  NODENAME                                         PROVIDERID                                          PHASE     AGE   VERSION
default            management-cluster-control-plane-mpx6g                        management-cluster       management-cluster-cp-c33f785a2d-9jgtx           openstack:///d0daa644-5c60-4264-b062-2d8dbf49eeb9   Running   23m   v1.26.7
workload-cluster   first-workload-cluster-control-plane-t7c4z                    first-workload-cluster   first-workload-cluster-cp-3735f85a7e-p6n82       openstack:///f1dbf552-8f11-4c29-b596-89b85d0be416   Running   20m   v1.27.3
workload-cluster   first-workload-cluster-worker-md-md0-699b77cf8bx4fbhz-6wffh   first-workload-cluster   first-workload-cluster-md-md0-1e6ba55e69-tv2w7   openstack:///24d5b349-e945-4e20-b588-77a154c9b899   Running   21m   v1.27.3+rke2r1
```
But after a few minutes the controlplane controller starts to fail:
```bash
rke2-bootstrap-system       rke2-bootstrap-controller-manager-68c4bc48f7-xbt4m               1/1     Running            0             28m
rke2-control-plane-system   rke2-control-plane-controller-manager-85bc4bc7c9-jlr98           1/1     Running            2 (34s ago)   28m
```
thowing this in the logs:
```bash
root@bastion-nis-nat:~/cm-tests/sylva-core# kubectl --kubeconfig management-cluster-kubeconfig -n rke2-control-plane-system logs rke2-control-plane-controller-manager-85bc4bc7c9-jlr98 --previous |tail -60
I0822 10:15:25.165271       1 controller.go:228]  "msg"="Starting workers" "controller"="rke2controlplane" "controllerGroup"="controlplane.cluster.x-k8s.io" "controllerKind"="RKE2ControlPlane" "worker count"=1
I0822 10:15:25.169297       1 rke2controlplane_controller.go:386]  "msg"="Reconcile RKE2 Control Plane" "RKE2ControlPlane"={"name":"first-workload-cluster-control-plane","namespace":"workload-cluster"} "controller"="rke2controlplane" "controllerGroup"="controlplane.cluster.x-k8s.io" "controllerKind"="RKE2ControlPlane" "name"="first-workload-cluster-control-plane" "namespace"="workload-cluster" "reconcileID"="ce569360-df7d-49bd-beac-1aae5ddbf109"
I0822 10:15:25.443102       1 controller.go:118]  "msg"="Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" "RKE2ControlPlane"={"name":"first-workload-cluster-control-plane","namespace":"workload-cluster"} "controller"="rke2controlplane" "controllerGroup"="controlplane.cluster.x-k8s.io" "controllerKind"="RKE2ControlPlane" "name"="first-workload-cluster-control-plane" "namespace"="workload-cluster" "reconcileID"="ce569360-df7d-49bd-beac-1aae5ddbf109"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12c3630]

goroutine 484 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x16cb1c0, 0x2798550})
        runtime/panic.go:884 +0x212
k8s.io/client-go/discovery.convertAPIResource(...)
        k8s.io/client-go@v0.26.1/discovery/aggregated_discovery.go:88
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc000727cc8, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        k8s.io/client-go@v0.26.1/discovery/aggregated_discovery.go:69 +0x5f0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc000726000, 0x15}, {0xc000be8aa0, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        k8s.io/client-go@v0.26.1/discovery/aggregated_discovery.go:35 +0x2f8
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0x18c5231?)
        k8s.io/client-go@v0.26.1/discovery/discovery_client.go:310 +0x47c
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0xc0004b83c0?)
        k8s.io/client-go@v0.26.1/discovery/discovery_client.go:198 +0x5c
k8s.io/client-go/discovery.ServerGroupsAndResources({0x1b53a28, 0xc0009ff470})
        k8s.io/client-go@v0.26.1/discovery/discovery_client.go:392 +0x59
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
        k8s.io/client-go@v0.26.1/discovery/discovery_client.go:356 +0x25
k8s.io/client-go/discovery.withRetries(0x2, 0xc000870ee0)
        k8s.io/client-go@v0.26.1/discovery/discovery_client.go:621 +0x72
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x0?)
        k8s.io/client-go@v0.26.1/discovery/discovery_client.go:355 +0x3a
k8s.io/client-go/restmapper.GetAPIGroupResources({0x1b53a28?, 0xc0009ff470?})
        k8s.io/client-go@v0.26.1/restmapper/discovery.go:148 +0x42
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper.func1()
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:94 +0x25
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).setStaticMapper(...)
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:130
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper(0xc000887d40?, {0x0, 0x0, 0x2?})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:110 +0x182
sigs.k8s.io/controller-runtime/pkg/client.newClient(0xc000887d40?, {0xc000226b60?, {0x0?, 0x0?}, {0xb8?, 0xd5?}})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/client.go:109 +0x212
sigs.k8s.io/controller-runtime/pkg/client.New(...)
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/client.go:77
github.com/rancher-sandbox/cluster-api-provider-rke2/pkg/rke2.(*Management).GetWorkloadCluster(0x1b5cc38?, {0x1b4d5b8?, 0xc0007482a0?}, {{0xc000c83980?, 0x0?}, {0xc0003c29d8?, 0x1?}})
        github.com/rancher-sandbox/cluster-api-provider-rke2/pkg/rke2/management_cluster.go:111 +0xcf
github.com/rancher-sandbox/cluster-api-provider-rke2/controlplane/internal/controllers.(*RKE2ControlPlaneReconciler).reconcileControlPlaneConditions(0xc000516310, {0x1b4d5b8, 0xc0007482a0}, 0xc00034f900)
        github.com/rancher-sandbox/cluster-api-provider-rke2/controlplane/internal/controllers/rke2controlplane_controller.go:680 +0x249
github.com/rancher-sandbox/cluster-api-provider-rke2/controlplane/internal/controllers.(*RKE2ControlPlaneReconciler).reconcileNormal(0xc000516310, {0x1b4d5b8, 0xc0007482a0}, 0xc000149040, 0xc0001e4100)
        github.com/rancher-sandbox/cluster-api-provider-rke2/controlplane/internal/controllers/rke2controlplane_controller.go:461 +0xb18
github.com/rancher-sandbox/cluster-api-provider-rke2/controlplane/internal/controllers.(*RKE2ControlPlaneReconciler).Reconcile(0xc000516310, {0x1b4d5b8, 0xc0007482a0}, {{{0xc000c839f0?, 0x10?}, {0xc000c88510?, 0x40daa7?}}})
        github.com/rancher-sandbox/cluster-api-provider-rke2/controlplane/internal/controllers/rke2controlplane_controller.go:183 +0x809
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1b4d5b8?, {0x1b4d5b8?, 0xc0007482a0?}, {{{0xc000c839f0?, 0x1648ca0?}, {0xc000c88510?, 0x0?}}})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000523220, {0x1b4d510, 0xc000602c40}, {0x1729880?, 0xc0004d20e0?})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x3a5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000523220, {0x1b4d510, 0xc000602c40})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x333
```
Are you using 1.26 for your management cluster? I don't think the problem appears if both clusters use the same version.

Thank you for the support

**Comment by belgaied2** [comment] 2023-08-30 14:09
Well @mavynet , I do have a management cluster in v1.26.4 and a workload cluster in v1.27.3:
```
$ docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED       STATUS       PORTS                              NAMES
16fd51d02bc6   kindest/node:v1.27.3                 "/usr/local/bin/entr…"   12 days ago   Up 2 hours   0/tcp, 127.0.0.1:32771->6443/tcp   rke2-1-27-control-plane-tglqn
b39539aef3b5   kindest/node:v1.27.3                 "/usr/local/bin/entr…"   12 days ago   Up 2 hours   0/tcp, 127.0.0.1:32770->6443/tcp   rke2-1-27-control-plane-zc5lj
a6111b7dca53   kindest/node:v1.27.3                 "/usr/local/bin/entr…"   12 days ago   Up 2 hours                                      rke2-1-27-worker-md-0-5db9b8cc6fxk9chl-p5z9f
5c4f14ac9f11   kindest/node:v1.27.3                 "/usr/local/bin/entr…"   12 days ago   Up 2 hours                                      rke2-1-27-worker-md-0-5db9b8cc6fxk9chl-vqc82
7e18cc43df89   kindest/node:v1.27.3                 "/usr/local/bin/entr…"   12 days ago   Up 2 hours   0/tcp, 127.0.0.1:32768->6443/tcp   rke2-1-27-control-plane-m9445
7b5e5c04042f   kindest/haproxy:v20230510-486859a6   "haproxy -W -db -f /…"   12 days ago   Up 2 hours   0/tcp, 0.0.0.0:32769->6443/tcp     rke2-1-27-lb
6943a29fb0cc   kindest/node:v1.26.4                 "/usr/local/bin/entr…"   13 days ago   Up 2 hours   127.0.0.1:46123->6443/tcp          capi-test-control-plane
b36bb85e2645   registry:2                           "/entrypoint.sh /etc…"   2 weeks ago   Up 2 hours   127.0.0.1:5000->5000/tcp           kind-registry
```

**Comment by mavynet** [comment] 2023-08-30 16:11
@belgaied2 my problem is not the cluster, it is correctly deployed. But after a couple of minutes the rke2 controller pod gets the error above and keeps restarting.

Can you check the pods in your management cluster?

**Comment by richardcase** [comment] 2023-09-18 16:00
We should also bump CAPI to 1.5.x as well as part of this.

**Comment by richardcase** [comment] 2023-11-16 17:11
We have bumped CAPI and k8s dependencies to enable this. Created a cluster with 1.27:

<img width="1383" alt="Screenshot 2023-11-16 at 17 10 27" src="https://github.com/rancher-sandbox/cluster-api-provider-rke2/assets/198425/bf82c93d-17fb-41a9-a65a-908ef33fef9c">


Therefore, closing this as completed.

**Closed by richardcase** 2023-11-16 17:11 UTC
Labels: kind/feature, needs-priority, triage/not-reproducible
